import React from 'react';
import { X, Printer, Landmark, CheckCircle2, ShieldCheck } from 'lucide-react';
import Logo from './Rammisbank_logo.png';

const AllotmentAdviceTemplate = ({ data, onClose }) => {
  return (
    <div className="fixed inset-0 bg-slate-900/90 backdrop-blur-md z-[200] flex items-center justify-center p-4 overflow-y-auto no-print-bg">
      <div id="advice-paper" className="bg-white w-full max-w-4xl p-12 shadow-2xl relative border-t-[12px] border-[#1a3b70] print:shadow-none print:m-0">
        
        {/* HEADER */}
        <div className="flex justify-between items-start border-b-2 border-slate-100 pb-8 mb-8">
           <div className="flex items-center gap-4">
              <img src={Logo} alt="Logo" className="w-16" />
              <div>
                 <h1 className="text-2xl font-black text-[#1a3b70] tracking-tighter uppercase">Rammis Bank S.C.</h1>
                 <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Share Department • Allotment Advice</p>
              </div>
           </div>
           <div className="text-right">
              <h2 className="text-xl font-black text-slate-800">ALLOTMENT ADVICE</h2>
              <p className="text-sm font-mono font-bold text-blue-600 mt-1">{data.allotment_ref}</p>
           </div>
        </div>

        {/* BODY */}
        <div className="space-y-8">
           <div className="flex justify-between">
              <div className="space-y-1">
                 <p className="text-[10px] font-black text-slate-400 uppercase">To the Shareholder:</p>
                 <p className="text-lg font-black text-slate-800">{data.full_name}</p>
                 <p className="text-xs font-bold text-slate-500">Member ID: {data.sh_code}</p>
              </div>
              <div className="text-right space-y-1">
                 <p className="text-[10px] font-black text-slate-400 uppercase">Effective Date:</p>
                 <p className="text-sm font-bold text-slate-700">{new Date(data.effective_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
              </div>
           </div>

           <div className="bg-slate-50 p-8 rounded-3xl border border-slate-100">
              <table className="w-full">
                 <thead>
                    <tr className="text-[10px] font-black text-slate-400 uppercase border-b border-slate-200">
                       <th className="pb-4 text-left">Description of Securities</th>
                       <th className="pb-4 text-center">Quantity</th>
                       <th className="pb-4 text-right">Total Value (ETB)</th>
                    </tr>
                 </thead>
                 <tbody>
                    <tr className="text-sm font-bold text-slate-700">
                       <td className="py-6">Ordinary Shares Allotted (Par Value 1,000)</td>
                       <td className="py-6 text-center">{data.shares_allotted?.toLocaleString()}</td>
                       <td className="py-6 text-right font-black text-[#1a3b70]">{Number(data.total_value).toLocaleString()}.00</td>
                    </tr>
                 </tbody>
                 <tfoot>
                    <tr className="border-t border-slate-200">
                       <td colSpan="2" className="pt-6 text-right text-[10px] font-black text-slate-400 uppercase">Amount Paid (Bank Ref: {data.payment_reference})</td>
                       <td className="pt-6 text-right text-lg font-black text-emerald-600">-{Number(data.amount_paid_at_allotment).toLocaleString()}.00</td>
                    </tr>
                    <tr>
                       <td colSpan="2" className="pt-2 text-right text-[10px] font-black text-slate-800 uppercase italic">Outstanding Balance Due</td>
                       <td className="pt-2 text-right text-xl font-black text-red-500">{(data.total_value - data.amount_paid_at_allotment).toLocaleString()}.00 ETB</td>
                    </tr>
                 </tfoot>
              </table>
           </div>

           <div className="pt-10 grid grid-cols-2 gap-20">
              <div className="space-y-4">
                 <div className="h-16 border-b border-slate-200 flex items-end justify-center pb-2 italic text-slate-300 text-xs">Registry Digital Signature</div>
                 <p className="text-[10px] font-black text-slate-400 uppercase text-center">Authorized Registrar</p>
              </div>
              <div className="bg-blue-50 p-6 rounded-2xl flex items-center gap-4 border border-blue-100">
                 <ShieldCheck size={32} className="text-blue-600" />
                 <p className="text-[9px] text-blue-800 font-medium leading-relaxed">
                    This document is automatically generated by the Rammis Bank Share Management System (SMS). It serves as a valid proof of allotment subject to final bank reconciliation.
                 </p>
              </div>
           </div>
        </div>

        {/* CONTROLS */}
        <div className="absolute top-6 right-6 flex gap-2 no-print">
          <button onClick={() => window.print()} className="p-3 bg-emerald-500 text-white rounded-xl shadow-lg hover:bg-emerald-600 transition-all"><Printer size={20}/></button>
          <button onClick={onClose} className="p-3 bg-red-500 text-white rounded-xl shadow-lg hover:bg-red-600 transition-all"><X size={20}/></button>
        </div>
      </div>

      <style>{`
        @media print {
          body { background: white !important; }
          .no-print { display: none !important; }
          #advice-paper { border: none !important; width: 100% !important; max-width: none !important; }
        }
      `}</style>
    </div>
  );
};

export default AllotmentAdviceTemplate;